### ISSUE TITLE
using bson-ext alone

### ISSUE THREAD

**Issue by slimee** [mongodb-js/bson-ext#46]
Hello

I would like to try bson-ext with node+rabbitmq in a microservices event sourcing application.

Please explain how to build and use bson-ext. I know node but not any native features, I try this:

yarn add bson-ext
yarn global add node-gyp
yarn add node-pre-gyp
node-gyp install

Running index.js with this line give an error:

require("bson-ext")

The error is:  "Could not locate the bindings file".

**Comment by mbroadst** [comment]
Hi @slimee, the error you are receiving would seem to indicate that building of the binding failed. Can you include more of your build logs? (npm/yarn should tell you where they are on failure). The best guess I can make from here is that you haven't installed a basic C++ toolchain on the system you are building this on.

**Comment by mabunassar** [comment]
Hello @mbroadst ,

I am using `mongodb` nodejs driver but having issues with very slow performance when trying to get results into an Array from cursor (using .toArray() -- also tried iterating over the cursor myself and didn't get any performance improvements). 

Mongo query executes in ~50ms according to mongo profiler; however, serialization seems to be taking a lot of time. Tried using `bson-ext`; however, I am running into the following issues:

When running `npm rebuild` in node_modules in project path. I get the following error:
```
> bson-ext@2.0.2 install {path-to-project}/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '{path-to-project}/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/src/bson.o
bson.target.mk:113: recipe for target 'Release/obj.target/bson/src/bson.o' failed
make: Leaving directory '{path-to-project}/node_modules/bson-ext/build'
```

When trying to import the library into one of the files in the project and run it, I get the following error:
```
{path-to-project}/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → {path-to-project}/node_modules/bson-ext/build/bson.node
 → {path-to-project}/node_modules/bson-ext/build/Debug/bson.node
 → {path-to-project}/node_modules/bson-ext/build/Release/bson.node
 → {path-to-project}/node_modules/bson-ext/out/Debug/bson.node
 → {path-to-project}/node_modules/bson-ext/Debug/bson.node
 → {path-to-project}/node_modules/bson-ext/out/Release/bson.node
 → {path-to-project}/node_modules/bson-ext/Release/bson.node
 → {path-to-project}/node_modules/bson-ext/build/default/bson.node
 → {path-to-project}/node_modules/bson-ext/compiled/12.3.1/linux/x64/bson.node
 → {path-to-project}/node_modules/bson-ext/addon-build/release/install-root/bson.node
 → {path-to-project}/node_modules/bson-ext/addon-build/debug/install-root/bson.node
 → {path-to-project}/node_modules/bson-ext/addon-build/default/install-root/bson.node
 → {path-to-project}/node_modules/bson-ext/lib/binding/node-v72-linux-x64/bson.node
    at bindings ({path-to-project}/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> ({path-to-project}/node_modules/bson-ext/lib/index.js:1:31)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module._compile ({path-to-project}/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.newLoader [as .js] ({path-to-project}/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.require ({path-to-project}/{file_name_where_bson-ext_is_imported})
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module._compile ({path-to-project}/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.newLoader [as .js] ({path-to-project}/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:641:32) {
  tries: [
    '/{path-to-project}/node_modules/bson-ext/build/bson.node',
    '{path-to-project}/node_modules/bson-ext/build/Debug/bson.node',
    '{path-to-project}/node_modules/bson-ext/build/Release/bson.node',
    '{path-to-project}/node_modules/bson-ext/out/Debug/bson.node',
    '{path-to-project}/node_modules/bson-ext/Debug/bson.node',
    '{path-to-project}/node_modules/bson-ext/out/Release/bson.node',
    '{path-to-project}/node_modules/bson-ext/Release/bson.node',
    '{path-to-project}/node_modules/bson-ext/build/default/bson.node',
    '{path-to-project}/node_modules/bson-ext/compiled/12.3.1/linux/x64/bson.node',
    '{path-to-project}/node_modules/bson-ext/addon-build/release/install-root/bson.node',
    '{path-to-project}/node_modules/bson-ext/addon-build/debug/install-root/bson.node',
    '{path-to-project}/node_modules/bson-ext/addon-build/default/install-root/bson.node',
    '{path-to-project}/node_modules/bson-ext/lib/binding/node-v72-linux-x64/bson.node'
  ]
```
Note that I have g++ installed on my machine.
