### ISSUE TITLE
bson-ext incompatible with latest mongodb package 3.2.2

### ISSUE THREAD

**Issue by clocked0ne** [mongodb-js/bson-ext#48]
If I do a clean package install and try to connect to a MongoDB replicaSet and insert a document using the Node driver (mongodb@3.2.2) it completes successfully.

If I then install `bson-ext` (2.0.1) and attempt the same process, I receive the following error:
``` Error: key $db must not start with '$'
      at Msg.serializeBson (node_modules\mongodb-core\lib\connection\msg.js:124:22)
      at Msg.makeDocumentSegment (node_modules\mongodb-core\lib\connection\msg.js:116:33)
      at Msg.toBin (node_modules\mongodb-core\lib\connection\msg.js:102:25)
      at serializeCommand (node_modules\mongodb-core\lib\connection\pool.js:771:41)
      at Pool.write (node_modules\mongodb-core\lib\connection\pool.js:928:3)
      at command (node_modules\mongodb-core\lib\wireprotocol\command.js:94:10)
      at writeCommand (node_modules\mongodb-core\lib\wireprotocol\write_command.js:47:3)
      at Object.insert (node_modules\mongodb-core\lib\wireprotocol\index.js:6:5)
      at Server.insert (node_modules\mongodb-core\lib\topologies\server.js:659:23)
      at executeWriteOperation (node_modules\mongodb-core\lib\topologies\replset.js:1183:37)
      at ReplSet.insert (node_modules\mongodb-core\lib\topologies\replset.js:1201:3)
      at ReplSet.insert (node_modules\mongodb\lib\topologies\topology_base.js:321:25)
      at insertDocuments (node_modules\mongodb\lib\operations\collection_ops.js:853:19)
      at insertOne (node_modules\mongodb\lib\operations\collection_ops.js:883:3)
      at C:\Users\horton01\Documents\GitHub\workray\node_modules\mongodb\lib\utils.js:433:24
      at new Promise (<anonymous>)
      at executeOperation (node_modules\mongodb\lib\utils.js:428:10)
      at Collection.insertOne (node_modules\mongodb\lib\collection.js:463:10)
      at connectDB.then (test\api\controllers\User.js:295:23)
      at process._tickCallback (internal/process/next_tick.js:68:7)```

Below is an example of the test `document` that is sent to `serializeBson` in `(node_modules\mongodb-core\lib\connection\msg.js:125:22`:

```
{ insert: 'Send_test',
  documents:
   [ { UserID: '5c4161678',
       RecordID: '389f21210',
       ActionCode: 'lapsed_users',
       Created: [Long],
       JSON:
        '{"FIRSTNAME":"Lucy Simmons","ENC_TOKEN":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUZXN0REVWIiwiZGF0YSI6Ijk4YzY5OGRhMGE4ZTQwMjUzMGM1MjIzZDc0YTdiZmNiIiwiaWF0IjoxNTQ3Nzg4NjU4LCJleHAiOjE1NzkzNDYyNTh9.vX7_qU--U3Wy7RVbhM2LsNDOqQ5g1vJMRIEsexEly-8$871b1e2206f187aa0974faef208f230a"}',
       LANG: 'EN',
       _id: 5ca4a0b9b9fd5641581b588c } ],
  ordered: true,
  lsid:
   { id:
      Binary {
        _bsontype: 'Binary',
        sub_type: 4,
        position: 16,
        buffer: <Buffer b7 f4 d5 53 b7 92 46 1f 83 b1 ff 2a 85 3a 9a 38> } },
  '$clusterTime':
   { clusterTime:
      Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1554292803 },
     signature: { hash: [Binary], keyId: [Long] } },
  '$db': 'emails' }
```

**Comment by danieler1981** [comment]
Same issue for me

**Comment by daprahamian** [comment]
Hi @clocked0ne @danieler1981,

Do you still see the error if you pass `checkKeys: false` to the options on your insert?

```js
collection.insertOne(doc, {checkKeys: false});
```

**Comment by clocked0ne** [comment]
@daprahamian No, if I pass `checkKeys: false` it works without error.

**Comment by daprahamian** [comment]
@clocked0ne @danieler1981 we just pushed `bson-ext@2.0.2` which should address your error.

**Comment by clocked0ne** [comment]
This has fixed the issue, we have re-instated it in our builds. Thanks for the quick turnaround!
